version: '3.8'
services:
  db:
    image: docker.io/library/postgres:13
    restart: always 
    user: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=lesha
      - POSTGRESQL_DIRECTORY=/home/lesha
    ports:
      - "5432:5432"
  web:
    build: .
    args:
      USERNAME: ${USERNAME}
      GROUPNAME: ${GROUPNAME}
      USERID: ${USERID}
      GROUPID: ${GROUPID}
    depends_on:
      - db
    environment:
      - TERMINFO=/etc/terminfo
      - TERM=xterm-256color
      - PGHOST=db
      - DATABASE_URL=postgresql://db
      - PGUSER=postgres
      - PGPASSWORD=password
      - APP_HOST=web
      - PAGER=nothing
      - APPDIR=api_project
    ports:
     - "3000:3000"
    volumes:
     - .:/app/api_project:z
